"use client";
import { useState } from "react";
const services=[["01","AI Automation","Turn repetitive work into smart workflows that run consistently."],["02","WhatsApp Automation","Organize inquiries, follow-ups and customer conversations into one system."],["03","Data & Spreadsheet Automation","Reduce manual data entry and connect everyday business information."],["04","Lead Recovery & Follow-Up","Build structured follow-up systems so opportunities do not get lost."],["05","Social Media & Advertising","Create, manage and optimize a consistent digital presence."],["06","Creative & AI Video","Premium visual content for products, campaigns and brand communication."]];
const steps=["Understand","Design","Build","Verify","Deliver"];
export default function Home(){const[open,setOpen]=useState<number|null>(null);return <main>
<nav className="nav"><a className="brand" href="#"><span>AMM</span><small>DATA SOLUTIONS</small></a><div className="navlinks"><a href="#solutions">Solutions</a><a href="#process">Process</a><a href="#about">About</a></div><a className="navcta" href="#contact">Start a project <i>↗</i></a></nav>
<section className="hero"><div className="orb orb1"/><div className="orb orb2"/><div className="heroGrid"/><div className="heroCopy"><div className="eyebrow"><span/> DIGITAL SYSTEMS · AI AUTOMATION</div><h1>Make your business<br/><em>work smarter.</em></h1><p>We turn repetitive business work into smart, organized and automated systems.</p><div className="heroActions"><a className="primary" href="#contact">Build a solution <b>→</b></a><a className="secondary" href="#solutions">Explore solutions</a></div></div><div className="systemVisual"><div className="visualCore"><strong>AMM</strong><span>SMART SYSTEM</span></div><div className="node nodeA"><b>INQUIRY</b><small>WhatsApp</small></div><div className="node nodeB"><b>DATA</b><small>Organized</small></div><div className="node nodeC"><b>FOLLOW-UP</b><small>Automated</small></div><div className="line l1"/><div className="line l2"/><div className="line l3"/></div><div className="heroBottom"><span>AMM DATA SOLUTIONS</span><span>LET’S MAKE SOLUTIONS</span><span>PAKISTAN · INTERNATIONAL</span></div></section>
<section className="intro section"><div className="sectionTag">01 / THE IDEA</div><div><h2>From scattered tasks<br/>to <span>connected systems.</span></h2><p className="lead">Your team should spend less time repeating the same work and more time moving the business forward. AMM designs practical digital systems around how your business actually operates.</p></div></section>
<section id="solutions" className="section solutions"><div className="sectionHead"><div><div className="sectionTag">02 / SOLUTIONS</div><h2>Built around the<br/><span>work that matters.</span></h2></div><p>Focused systems. Clear workflows. Useful automation. No unnecessary complexity.</p></div><div className="serviceGrid">{services.map((s,i)=><article className={"service "+(open===i?"active":"")} key={s[0]} onClick={()=>setOpen(open===i?null:i)}><div className="serviceTop"><span>{s[0]}</span><span>{open===i?"−":"+"}</span></div><h3>{s[1]}</h3><p>{s[2]}</p><div className="serviceArrow">↗</div></article>)}</div></section>
<section className="demo section"><div className="sectionTag">03 / BEFORE → AFTER</div><div className="demoWrap"><div className="demoPanel before"><label>BEFORE</label><h3>Manual business flow</h3>{["Message arrives","Someone checks it","Data copied manually","Follow-up remembered later"].map((x,i)=><div className="task" key={x}><span>0{i+1}</span>{x}</div>)}</div><div className="transform">→<small>AMM SYSTEM</small></div><div className="demoPanel after"><label>AFTER</label><h3>Connected workflow</h3>{["Inquiry captured","Information organized","Follow-up triggered","Team stays in control"].map((x,i)=><div className="task activeTask" key={x}><span>0{i+1}</span>{x}<b>✓</b></div>)}</div></div></section>
<section id="process" className="section process"><div className="sectionTag">04 / HOW WE WORK</div><h2>Simple process.<br/><span>Serious execution.</span></h2><div className="steps">{steps.map((s,i)=><div className="step" key={s}><span>0{i+1}</span><div><h3>{s}</h3><p>{["Understand your workflow, goals and bottlenecks.","Map the right experience before building.","Develop the system with practical tools and clean UX.","Test the important paths and remove friction.","Hand over a usable solution with clear next steps."][i]}</p></div></div>)}</div></section>
<section id="about" className="about section"><div className="aboutCard"><div className="sectionTag">05 / AMM</div><div className="aboutMark">AMM<span>DATA SOLUTIONS</span></div><p>We combine automation, data, digital systems and creative production to help growing businesses operate with more structure.</p><div className="pillRow"><span>Practical</span><span>Modern</span><span>Reliable</span><span>Technology-driven</span></div></div><div className="aboutSide"><div className="miniLabel">WHAT WE OPTIMIZE</div>{[["TIME","Less repetitive work"],["FLOW","Clearer business processes"],["CONTROL","Better visibility for teams"],["GROWTH","Systems ready to scale"]].map(x=><div className="metric" key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></section>
<section id="contact" className="contact section"><div className="contactGlow"/><div className="sectionTag">06 / START HERE</div><h2>Have a process that<br/><span>should be smarter?</span></h2><p>Tell us what is taking too much time. We’ll turn the problem into a practical digital solution.</p><a className="primary large" href="mailto:bammdatasolutins229@gmail.com">Discuss your project <b>↗</b></a></section>
<footer><div className="footerBrand"><strong>AMM</strong><span>DATA SOLUTIONS</span></div><p>AI Automation · Business Systems · Digital Solutions · Creative Services</p><div>© 2026 AMM Data Solutions</div></footer></main>}